### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Drc-DEV** [MC-Resources-Store/message-blocker#2]
https://pastebin.com/WpwA2Wpx

Version 1.0.2 on Paper 1.15.2

**Comment by Krymonota** [comment]
How often does this error occur? I'd also need your plugin configuration.

**Comment by Drc-DEV** [comment]
```
blocked:
  - message: 'Respawn point set'
    mode: 'contains'
    ignore_case: true
```

Just noticed it, since it started appearing, it just floods the console until restart.

**Comment by Krymonota** [comment]
Please try adding `bypass_permission:` to the entry:
```yaml
blocked:
  - message: 'Respawn point set'
    mode: 'contains'
    ignore_case: true
    bypass_permission:
```
